# Generated by Django 5.2 on 2025-05-30 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyBookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wert', models.CharField(max_length=200)),
                ('fileofproperty', models.FileField(upload_to='')),
                ('bookinstanceuuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.bookinstance')),
            ],
        ),
    ]
